// Lista completa de ícones disponíveis para grupos e abas
export const iconOptions = [
  // Comunicação
  { value: 'message-circle', label: 'Mensagem' },
  { value: 'message-square', label: 'Chat' },
  { value: 'messages-square', label: 'Conversas' },
  { value: 'mail', label: 'Email' },
  { value: 'inbox', label: 'Caixa de entrada' },
  { value: 'send', label: 'Enviar' },
  { value: 'phone', label: 'Telefone' },
  { value: 'phone-call', label: 'Ligação' },
  { value: 'video', label: 'Vídeo' },
  { value: 'headphones', label: 'Suporte' },
  { value: 'mic', label: 'Microfone' },
  { value: 'bell', label: 'Notificação' },
  { value: 'megaphone', label: 'Megafone' },
  { value: 'at-sign', label: 'Arroba' },
  
  // Arquivos e documentos
  { value: 'folder', label: 'Pasta' },
  { value: 'folder-open', label: 'Pasta aberta' },
  { value: 'file', label: 'Arquivo' },
  { value: 'file-text', label: 'Documento' },
  { value: 'files', label: 'Arquivos' },
  { value: 'file-check', label: 'Arquivo OK' },
  { value: 'file-plus', label: 'Novo arquivo' },
  { value: 'file-spreadsheet', label: 'Planilha' },
  { value: 'file-image', label: 'Imagem' },
  { value: 'file-video', label: 'Vídeo arquivo' },
  { value: 'file-audio', label: 'Áudio' },
  { value: 'file-code', label: 'Código' },
  { value: 'clipboard', label: 'Área transferência' },
  { value: 'clipboard-list', label: 'Lista tarefas' },
  { value: 'book', label: 'Livro' },
  { value: 'book-open', label: 'Livro aberto' },
  { value: 'notebook', label: 'Caderno' },
  { value: 'newspaper', label: 'Jornal' },
  
  // Web e navegação
  { value: 'globe', label: 'Web' },
  { value: 'globe-2', label: 'Globo' },
  { value: 'link', label: 'Link' },
  { value: 'link-2', label: 'Conexão' },
  { value: 'external-link', label: 'Link externo' },
  { value: 'compass', label: 'Bússola' },
  { value: 'navigation', label: 'Navegação' },
  { value: 'map', label: 'Mapa' },
  { value: 'map-pin', label: 'Localização' },
  { value: 'home', label: 'Home' },
  { value: 'building', label: 'Prédio' },
  { value: 'building-2', label: 'Empresa' },
  { value: 'store', label: 'Loja' },
  { value: 'warehouse', label: 'Depósito' },
  
  // Financeiro e negócios
  { value: 'dollar-sign', label: 'Dólar' },
  { value: 'credit-card', label: 'Cartão' },
  { value: 'wallet', label: 'Carteira' },
  { value: 'banknote', label: 'Dinheiro' },
  { value: 'coins', label: 'Moedas' },
  { value: 'piggy-bank', label: 'Cofre' },
  { value: 'receipt', label: 'Recibo' },
  { value: 'calculator', label: 'Calculadora' },
  { value: 'percent', label: 'Porcentagem' },
  { value: 'trending-up', label: 'Crescimento' },
  { value: 'trending-down', label: 'Queda' },
  { value: 'bar-chart', label: 'Gráfico barras' },
  { value: 'bar-chart-2', label: 'Estatísticas' },
  { value: 'pie-chart', label: 'Gráfico pizza' },
  { value: 'line-chart', label: 'Gráfico linha' },
  { value: 'activity', label: 'Atividade' },
  
  // Pessoas e equipe
  { value: 'user', label: 'Usuário' },
  { value: 'users', label: 'Equipe' },
  { value: 'user-plus', label: 'Novo usuário' },
  { value: 'user-check', label: 'Usuário OK' },
  { value: 'user-cog', label: 'Config usuário' },
  { value: 'contact', label: 'Contato' },
  { value: 'contact-2', label: 'Contatos' },
  { value: 'hand-shake', label: 'Parceria' },
  { value: 'smile', label: 'Sorriso' },
  { value: 'heart', label: 'Favorito' },
  { value: 'thumbs-up', label: 'Curtir' },
  { value: 'star', label: 'Estrela' },
  { value: 'award', label: 'Prêmio' },
  { value: 'trophy', label: 'Troféu' },
  { value: 'crown', label: 'Coroa' },
  
  // Produtividade e organização
  { value: 'calendar', label: 'Calendário' },
  { value: 'calendar-days', label: 'Agenda' },
  { value: 'calendar-check', label: 'Evento OK' },
  { value: 'clock', label: 'Relógio' },
  { value: 'timer', label: 'Timer' },
  { value: 'alarm-clock', label: 'Alarme' },
  { value: 'hourglass', label: 'Ampulheta' },
  { value: 'check', label: 'Check' },
  { value: 'check-circle', label: 'Concluído' },
  { value: 'check-square', label: 'Checkbox' },
  { value: 'list', label: 'Lista' },
  { value: 'list-todo', label: 'Tarefas' },
  { value: 'list-checks', label: 'Checklist' },
  { value: 'kanban', label: 'Kanban' },
  { value: 'layout-grid', label: 'Grid' },
  { value: 'layout-list', label: 'Lista layout' },
  { value: 'layers', label: 'Camadas' },
  { value: 'filter', label: 'Filtro' },
  { value: 'search', label: 'Busca' },
  { value: 'tag', label: 'Tag' },
  { value: 'tags', label: 'Tags' },
  { value: 'bookmark', label: 'Marcador' },
  { value: 'flag', label: 'Bandeira' },
  { value: 'pin', label: 'Pin' },
  { value: 'target', label: 'Objetivo' },
  { value: 'crosshair', label: 'Foco' },
  
  // Vendas e e-commerce
  { value: 'shopping-cart', label: 'Carrinho' },
  { value: 'shopping-bag', label: 'Sacola' },
  { value: 'shopping-basket', label: 'Cesta' },
  { value: 'package', label: 'Pacote' },
  { value: 'box', label: 'Caixa' },
  { value: 'gift', label: 'Presente' },
  { value: 'truck', label: 'Entrega' },
  { value: 'ship', label: 'Navio' },
  { value: 'plane', label: 'Avião' },
  { value: 'car', label: 'Carro' },
  { value: 'bike', label: 'Bicicleta' },
  
  // Tecnologia e desenvolvimento
  { value: 'code', label: 'Código' },
  { value: 'code-2', label: 'Programação' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'bug', label: 'Bug' },
  { value: 'database', label: 'Banco dados' },
  { value: 'server', label: 'Servidor' },
  { value: 'cloud', label: 'Nuvem' },
  { value: 'cpu', label: 'Processador' },
  { value: 'hard-drive', label: 'HD' },
  { value: 'smartphone', label: 'Celular' },
  { value: 'tablet', label: 'Tablet' },
  { value: 'laptop', label: 'Notebook' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'tv', label: 'TV' },
  { value: 'wifi', label: 'WiFi' },
  { value: 'bluetooth', label: 'Bluetooth' },
  { value: 'usb', label: 'USB' },
  { value: 'plug', label: 'Plug' },
  { value: 'zap', label: 'Raio' },
  { value: 'battery', label: 'Bateria' },
  
  // Segurança e configurações
  { value: 'settings', label: 'Configurações' },
  { value: 'settings-2', label: 'Ajustes' },
  { value: 'sliders', label: 'Controles' },
  { value: 'wrench', label: 'Ferramenta' },
  { value: 'tool', label: 'Chave' },
  { value: 'hammer', label: 'Martelo' },
  { value: 'lock', label: 'Cadeado' },
  { value: 'unlock', label: 'Desbloqueado' },
  { value: 'key', label: 'Chave acesso' },
  { value: 'shield', label: 'Escudo' },
  { value: 'shield-check', label: 'Seguro' },
  { value: 'eye', label: 'Visualizar' },
  { value: 'eye-off', label: 'Ocultar' },
  { value: 'fingerprint', label: 'Biometria' },
  { value: 'scan', label: 'Scan' },
  { value: 'qr-code', label: 'QR Code' },
  
  // Mídia e entretenimento
  { value: 'image', label: 'Imagem' },
  { value: 'images', label: 'Galeria' },
  { value: 'camera', label: 'Câmera' },
  { value: 'film', label: 'Filme' },
  { value: 'music', label: 'Música' },
  { value: 'music-2', label: 'Áudio' },
  { value: 'radio', label: 'Rádio' },
  { value: 'play', label: 'Play' },
  { value: 'play-circle', label: 'Reproduzir' },
  { value: 'youtube', label: 'YouTube' },
  { value: 'twitch', label: 'Twitch' },
  { value: 'gamepad', label: 'Games' },
  { value: 'gamepad-2', label: 'Jogos' },
  { value: 'palette', label: 'Design' },
  { value: 'brush', label: 'Pincel' },
  { value: 'pen-tool', label: 'Caneta' },
  { value: 'pencil', label: 'Lápis' },
  { value: 'eraser', label: 'Borracha' },
  { value: 'ruler', label: 'Régua' },
  { value: 'scissors', label: 'Tesoura' },
  
  // Redes sociais e marcas
  { value: 'instagram', label: 'Instagram' },
  { value: 'facebook', label: 'Facebook' },
  { value: 'twitter', label: 'Twitter' },
  { value: 'linkedin', label: 'LinkedIn' },
  { value: 'github', label: 'GitHub' },
  { value: 'gitlab', label: 'GitLab' },
  { value: 'figma', label: 'Figma' },
  { value: 'slack', label: 'Slack' },
  { value: 'trello', label: 'Trello' },
  { value: 'chrome', label: 'Chrome' },
  
  // Educação e aprendizado
  { value: 'graduation-cap', label: 'Formação' },
  { value: 'school', label: 'Escola' },
  { value: 'library', label: 'Biblioteca' },
  { value: 'lightbulb', label: 'Ideia' },
  { value: 'brain', label: 'Cérebro' },
  { value: 'sparkles', label: 'Brilho' },
  { value: 'wand-2', label: 'Varinha' },
  { value: 'flask', label: 'Laboratório' },
  { value: 'atom', label: 'Átomo' },
  { value: 'beaker', label: 'Béquer' },
  { value: 'microscope', label: 'Microscópio' },
  { value: 'telescope', label: 'Telescópio' },
  
  // Saúde e bem-estar
  { value: 'heart-pulse', label: 'Saúde' },
  { value: 'stethoscope', label: 'Médico' },
  { value: 'pill', label: 'Remédio' },
  { value: 'syringe', label: 'Vacina' },
  { value: 'thermometer', label: 'Temperatura' },
  { value: 'apple', label: 'Maçã' },
  { value: 'salad', label: 'Salada' },
  { value: 'coffee', label: 'Café' },
  { value: 'utensils', label: 'Restaurante' },
  { value: 'beer', label: 'Cerveja' },
  { value: 'wine', label: 'Vinho' },
  { value: 'dumbbell', label: 'Academia' },
  { value: 'footprints', label: 'Passos' },
  { value: 'bike', label: 'Ciclismo' },
  
  // Natureza e clima
  { value: 'sun', label: 'Sol' },
  { value: 'moon', label: 'Lua' },
  { value: 'cloud-sun', label: 'Parcialmente nublado' },
  { value: 'cloud-rain', label: 'Chuva' },
  { value: 'snowflake', label: 'Neve' },
  { value: 'wind', label: 'Vento' },
  { value: 'umbrella', label: 'Guarda-chuva' },
  { value: 'tree-deciduous', label: 'Árvore' },
  { value: 'flower', label: 'Flor' },
  { value: 'leaf', label: 'Folha' },
  { value: 'mountain', label: 'Montanha' },
  { value: 'waves', label: 'Ondas' },
  { value: 'fish', label: 'Peixe' },
  { value: 'bird', label: 'Pássaro' },
  { value: 'dog', label: 'Cachorro' },
  { value: 'cat', label: 'Gato' },
  { value: 'paw-print', label: 'Patinha' },
  
  // Outros úteis
  { value: 'hash', label: 'Hash' },
  { value: 'asterisk', label: 'Asterisco' },
  { value: 'info', label: 'Info' },
  { value: 'help-circle', label: 'Ajuda' },
  { value: 'alert-circle', label: 'Alerta' },
  { value: 'alert-triangle', label: 'Aviso' },
  { value: 'x-circle', label: 'Erro' },
  { value: 'plus-circle', label: 'Adicionar' },
  { value: 'minus-circle', label: 'Remover' },
  { value: 'arrow-right', label: 'Seta direita' },
  { value: 'arrow-left', label: 'Seta esquerda' },
  { value: 'arrow-up', label: 'Seta cima' },
  { value: 'arrow-down', label: 'Seta baixo' },
  { value: 'refresh-cw', label: 'Atualizar' },
  { value: 'rotate-cw', label: 'Rotacionar' },
  { value: 'download', label: 'Download' },
  { value: 'upload', label: 'Upload' },
  { value: 'share', label: 'Compartilhar' },
  { value: 'share-2', label: 'Enviar' },
  { value: 'copy', label: 'Copiar' },
  { value: 'move', label: 'Mover' },
  { value: 'maximize', label: 'Maximizar' },
  { value: 'minimize', label: 'Minimizar' },
  { value: 'expand', label: 'Expandir' },
  { value: 'shrink', label: 'Encolher' },
  { value: 'fullscreen', label: 'Tela cheia' },
  { value: 'grid', label: 'Grade' },
  { value: 'menu', label: 'Menu' },
  { value: 'more-horizontal', label: 'Mais' },
  { value: 'more-vertical', label: 'Opções' },
  { value: 'ellipsis', label: 'Reticências' },
  { value: 'power', label: 'Power' },
  { value: 'log-in', label: 'Login' },
  { value: 'log-out', label: 'Logout' },
  { value: 'save', label: 'Salvar' },
  { value: 'trash', label: 'Lixeira' },
  { value: 'trash-2', label: 'Excluir' },
  { value: 'archive', label: 'Arquivo' },
  { value: 'printer', label: 'Impressora' },
  { value: 'scan-line', label: 'Scanner' },
  { value: 'voicemail', label: 'Voicemail' },
  { value: 'rss', label: 'RSS' },
  { value: 'podcast', label: 'Podcast' },
  { value: 'rocket', label: 'Foguete' },
  { value: 'flame', label: 'Chama' },
  { value: 'gem', label: 'Gema' },
  { value: 'anchor', label: 'Âncora' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'blocks', label: 'Blocos' },
  { value: 'component', label: 'Componente' },
  { value: 'box-select', label: 'Seleção' },
];

// Lista de cores disponíveis
export const colorOptions = [
  { value: '#6366f1', label: 'Índigo' },
  { value: '#22d3ee', label: 'Ciano' },
  { value: '#10b981', label: 'Verde' },
  { value: '#22c55e', label: 'Verde claro' },
  { value: '#84cc16', label: 'Lima' },
  { value: '#eab308', label: 'Amarelo' },
  { value: '#f59e0b', label: 'Laranja' },
  { value: '#f97316', label: 'Laranja escuro' },
  { value: '#ef4444', label: 'Vermelho' },
  { value: '#dc2626', label: 'Vermelho escuro' },
  { value: '#ec4899', label: 'Rosa' },
  { value: '#d946ef', label: 'Fúcsia' },
  { value: '#a855f7', label: 'Púrpura' },
  { value: '#8b5cf6', label: 'Roxo' },
  { value: '#3b82f6', label: 'Azul' },
  { value: '#0ea5e9', label: 'Azul céu' },
  { value: '#06b6d4', label: 'Turquesa' },
  { value: '#14b8a6', label: 'Teal' },
  { value: '#64748b', label: 'Cinza' },
  { value: '#78716c', label: 'Marrom' },
];
